import type { PointOfInterest } from './types';

// ─── RESTAURANTES REALES ─────────────────────────────────────
export const restaurants: PointOfInterest[] = [
  // VALDERROBRES
  { id:"fonda_angeleta", name:"Fonda Angeleta", category:"restaurante", subcategory:"Cocina tradicional", location:"Valderrobres", lat:40.8742, lng:0.1555, description:"De los más recomendados de Valderrobres. Fantástica relación calidad/precio con cocina aragonesa tradicional.", image:"/img/fonda_angeleta.png", phone:"978 850 192", priceRange:"€€", rating:4.6, recommended:true, specialties:["Ternasco al horno","Migas aragonesas","Cocina tradicional"], productClub:"gastronomia", externalUrl:"https://www.google.com/maps/search/?api=1&query=Fonda+Angeleta+Valderrobres", externalLabel:"Ver en Maps" },
  { id:"gastrobar_elias", name:"Gastrobar Elías", category:"restaurante", subcategory:"Gastrobar", location:"Valderrobres", lat:40.8738, lng:0.1562, description:"Tapas creativas y raciones generosas en el centro de Valderrobres.", priceRange:"€€", rating:4.4, specialties:["Tapas creativas","Raciones"], externalUrl:"https://www.google.com/maps/search/?api=1&query=Gastrobar+Elias+Valderrobres" },
  { id:"baudilio", name:"Baudilio por Fabiana Arévalo", category:"restaurante", subcategory:"Cocina de autor", location:"Valderrobres", lat:40.8735, lng:0.1548, description:"Propuesta gastronómica premium con cocina de autor aragonesa y toques contemporáneos.", priceRange:"€€€", rating:4.7, recommended:true, specialties:["Menú degustación","Cocina de autor","Producto local"], externalUrl:"https://www.google.com/maps/search/?api=1&query=Restaurante+Baudilio+Valderrobres" },
  { id:"lo_coscoll", name:"Lo Coscoll Cocina a la Leña", category:"restaurante", subcategory:"Asador", location:"Valderrobres", lat:40.8745, lng:0.1570, description:"Especialidad en cocina a la leña. Carnes y verduras a la brasa con sabor auténtico.", priceRange:"€€", rating:4.5, specialties:["Cocina a la leña","Carnes a la brasa","Verduras asadas"], externalUrl:"https://www.google.com/maps/search/?api=1&query=Lo+Coscoll+Valderrobres" },
  { id:"matarranya_al_gust", name:"Matarraña Al Gust", category:"restaurante", subcategory:"Cocina local", location:"Valderrobres", lat:40.8748, lng:0.1552, description:"Buen trato y calidad-precio. Cocina local con productos de proximidad.", priceRange:"€", rating:4.3, specialties:["Cocina del día","Menú casero","Producto local"], externalUrl:"https://www.google.com/maps/search/?api=1&query=Matarraña+al+Gust+Valderrobres" },
  { id:"hotel_el_salt", name:"Hotel Restaurante El Salt", category:"restaurante", subcategory:"Cocina regional", location:"Valderrobres", lat:40.8750, lng:0.1540, description:"Ambiente acogedor con personal amable. Cocina regional aragonesa de calidad.", priceRange:"€€", rating:4.3, specialties:["Cocina regional","Ambiente acogedor"], externalUrl:"https://www.google.com/maps/search/?api=1&query=Hotel+Restaurante+El+Salt+Valderrobres" },
  { id:"somiar", name:"Restaurante Somiar", category:"restaurante", subcategory:"Cocina creativa", location:"Valderrobres", lat:40.8740, lng:0.1565, description:"Cocina creativa en el corazón de la capital del Matarraña.", priceRange:"€€", rating:4.2, specialties:["Cocina creativa","Menú degustación"], externalUrl:"https://www.google.com/maps/search/?api=1&query=Restaurante+Somiar+Valderrobres" },
  { id:"pasteleria_sanz", name:"Pastelería Sanz", category:"restaurante", subcategory:"Pastelería", location:"Valderrobres", lat:40.8743, lng:0.1558, description:"Dulces artesanales del Matarraña: casquetas, almendrados, carquiñolis y más.", priceRange:"€", rating:4.5, specialties:["Casquetas","Almendrados","Carquiñolis","Mantecados"], externalUrl:"https://www.google.com/maps/search/?api=1&query=Pasteleria+Sanz+Valderrobres" },
  // BECEITE
  { id:"font_del_pas", name:"Font del Pas", category:"restaurante", subcategory:"Cocina especial", location:"Beceite", lat:40.8292, lng:0.1735, description:"Menús elaborados para comidas especiales. Una de las mejores experiencias gastronómicas de Beceite.", priceRange:"€€€", rating:4.7, recommended:true, specialties:["Menú elaborado","Comidas especiales","Producto del Matarraña"], productClub:"gastronomia", externalUrl:"https://www.google.com/maps/search/?api=1&query=Font+del+Pas+Beceite", externalLabel:"Ver en Maps" },
  { id:"antigua_posada_roda", name:"Antigua Posada Roda", category:"restaurante", subcategory:"Cocina tradicional", location:"Beceite", lat:40.8288, lng:0.1742, description:"Cocina tradicional y casera con especialidades locales. Muy recomendado por los visitantes.", priceRange:"€€", rating:4.5, recommended:true, specialties:["Cocina casera","Especialidades locales","Ternasco"], productClub:"gastronomia", externalUrl:"https://www.google.com/maps/search/?api=1&query=Antigua+Posada+Roda+Beceite" },
  { id:"fabrica_solfa", name:"La Fábrica de Solfa", category:"restaurante", subcategory:"Restaurante gastronómico", location:"Beceite", lat:40.8285, lng:0.1730, description:"Hotel boutique + restaurante gastronómico. Propuesta basada en producto local de temporada.", priceRange:"€€€", rating:4.6, recommended:true, specialties:["Menú degustación","Producto de temporada","Vinos D.O."], productClub:"gastronomia", externalUrl:"https://www.google.com/maps/search/?api=1&query=La+Fabrica+de+Solfa+Beceite" },
  { id:"la_rabosa", name:"La Rabosa", category:"restaurante", subcategory:"Cocina casera", location:"Beceite", lat:40.8300, lng:0.1820, description:"Junto a La Pesquera. Comida casera, menús variados y raciones abundantes. Ideal post-baño.", priceRange:"€", rating:4.2, specialties:["Menú del día","Raciones","Cocina casera"], externalUrl:"https://www.google.com/maps/search/?api=1&query=La+Rabosa+Beceite" },
  { id:"raco_tosca", name:"Asador Racó del Toscá", category:"restaurante", subcategory:"Asador", location:"Beceite", lat:40.8295, lng:0.1748, description:"Asador con carnes a la brasa en un entorno rústico con encanto.", priceRange:"€€", rating:4.3, specialties:["Carnes a la brasa","Embutidos","Cocina rústica"], externalUrl:"https://www.google.com/maps/search/?api=1&query=Raco+del+Tosca+Beceite" },
  // CALACEITE
  { id:"fonda_alcala", name:"Fonda Alcalá", category:"restaurante", subcategory:"Cocina tradicional/innovación", location:"Calaceite", lat:41.0192, lng:0.1875, description:"Menú degustación con toques de innovación. Reconocido como uno de los mejores de la comarca.", priceRange:"€€", rating:4.7, recommended:true, specialties:["Menú degustación","Cocina innovadora","Producto Km0"], productClub:"gastronomia", externalUrl:"https://www.google.com/maps/search/?api=1&query=Fonda+Alcala+Calaceite" },
  { id:"la_cantonada", name:"La Cantonada", category:"restaurante", subcategory:"Bar tapas", location:"Calaceite", lat:41.0188, lng:0.1882, description:"Bar informal para tapas, raciones y aperitivos. Económico y con buen ambiente.", priceRange:"€", rating:4.1, specialties:["Tapas","Raciones","Aperitivos"], externalUrl:"https://www.google.com/maps/search/?api=1&query=La+Cantonada+Calaceite" },
  { id:"hotel_sitjar", name:"Hotel del Sitjar", category:"restaurante", subcategory:"Restaurante con vistas", location:"Calaceite", lat:41.0195, lng:0.1870, description:"Restaurante con vistas panorámicas. Cocina regional en un entorno privilegiado.", priceRange:"€€", rating:4.3, specialties:["Cocina regional","Vistas panorámicas"], externalUrl:"https://www.google.com/maps/search/?api=1&query=Hotel+del+Sitjar+Calaceite" },
  { id:"calixto", name:"Restaurante Calixto", category:"restaurante", subcategory:"Cocina regional", location:"Calaceite", lat:41.0185, lng:0.1885, description:"Cocina regional aragonesa con productos de la tierra en pleno centro de Calaceite.", priceRange:"€€", rating:4.2, specialties:["Cocina aragonesa","Producto local"], externalUrl:"https://www.google.com/maps/search/?api=1&query=Restaurante+Calixto+Calaceite" },
  { id:"da_capo", name:"Da Capo", category:"restaurante", subcategory:"Cocina mediterránea", location:"Calaceite", lat:41.0190, lng:0.1890, description:"Cocina mediterránea con influencias italianas en un pueblo de piedra.", priceRange:"€€", rating:4.3, specialties:["Cocina mediterránea","Pasta fresca","Pizzas"], externalUrl:"https://www.google.com/maps/search/?api=1&query=Da+Capo+Calaceite" },
  // LA FRESNEDA
  { id:"restaurante_matarranya", name:"Restaurante Matarraña", category:"restaurante", subcategory:"Cocina de proximidad", location:"La Fresneda", lat:40.9252, lng:0.0695, description:"Cocina tradicional y de proximidad. Referente de la gastronomía matarrañera.", priceRange:"€€", rating:4.5, recommended:true, specialties:["Cocina de proximidad","Ternasco","Producto local"], productClub:"gastronomia", externalUrl:"https://restaurantematarranya.com", externalLabel:"restaurantematarranya.com" },
  { id:"el_convent", name:"El Convent", category:"restaurante", subcategory:"Hotel boutique + restaurante", location:"La Fresneda", lat:40.9248, lng:0.0705, description:"Hotel boutique con restaurante en un antiguo convento. Cocina selecta con vistas.", priceRange:"€€€", rating:4.5, specialties:["Cocina selecta","Ambiente histórico","Vistas"], productClub:"gastronomia", externalUrl:"https://www.hotelelconvent.com", externalLabel:"hotelelconvent.com" },
  // OTROS PUEBLOS
  { id:"torre_del_visco", name:"La Torre del Visco", category:"restaurante", subcategory:"Hotel 5★ + restaurante", location:"Fuentespalda", lat:40.8100, lng:0.0200, description:"Hotel 5 estrellas con restaurante de alta cocina. Una experiencia gastronómica única en el Matarraña.", priceRange:"€€€", rating:4.8, recommended:true, specialties:["Alta cocina","Producto Km0","Experiencia 5★"], productClub:"gastronomia", externalUrl:"https://www.torredelvisco.com", externalLabel:"torredelvisco.com" },
  { id:"la_alqueria", name:"La Alquería", category:"restaurante", subcategory:"Michelin recommended", location:"Ráfales", lat:40.8600, lng:0.0100, description:"Recomendado por la Guía Michelin. Cocina rural de alta calidad con productos de la comarca.", priceRange:"€€€", rating:4.6, recommended:true, specialties:["Guía Michelin","Cocina rural premium","Producto Km0"], productClub:"gastronomia", externalUrl:"https://www.google.com/maps/search/?api=1&query=La+Alqueria+Rafales" },
];

// ─── TURISMO ACTIVO ──────────────────────────────────────────
export const activities: PointOfInterest[] = [
  { id:"bike_park", name:"Bike Park Fuentespalda", category:"actividad", subcategory:"Mountain Bike DH", location:"Fuentespalda", lat:40.8105, lng:0.0210, description:"5 pistas de descenso (DH) con desnivel de 290m. Niveles medio, avanzado y experto. Servicio de remonte.", image:"/img/bike_park.png", longDescription:"El Bike Park de Fuentespalda, inaugurado en 2026, cuenta con 5 líneas de descenso entre 2,2 y 2,6 km. Pistas con peraltes, drops, wallrides y pasarelas de madera. Finaliza en el Matarraña Dirt Park para aprendizaje. Integrado en la Red Ciclista del Matarraña. Servicio de remonte para maximizar bajadas.", recommended:true, specialties:["5 pistas DH","Desnivel 290m","Servicio remonte","Dirt Park","Todo el año"], productClub:"cicloturismo", externalUrl:"https://www.comarcamatarranya.es/turismo/bike-park-fuentespalda", externalLabel:"Más info Bike Park", tips:["Nivel medio a experto — lleva casco integral","Servicio de remonte incluido","Abierto todo el año"] },
  { id:"tirolina", name:"Tirolina de Fuentespalda", category:"actividad", subcategory:"Adrenalina pura", location:"Fuentespalda", lat:40.8110, lng:0.0215, description:"¡La tirolina más larga de España! 2 km de recorrido, 200m de desnivel, hasta 120 km/h. Tirolina doble.", image:"/img/tirolina.png", longDescription:"2 kilómetros de pura adrenalina con un desnivel de 200 metros y velocidades de hasta 120 km/h. Es una tirolina doble para lanzarse en pareja. Peso mínimo 50 kg. Accesible para personas con movilidad reducida. ¡También saltos nocturnos!", recommended:true, specialties:["2 km de recorrido","120 km/h","Tirolina doble","Saltos nocturnos","Accesible PMR"], tips:["Reserva con antelación — se agotan plazas","Peso mínimo 50 kg","Menores acompañados de adulto","¡Hay saltos nocturnos!"] },
  { id:"mas_bunyol", name:"Mas de Bunyol — Buitreman", category:"actividad", subcategory:"Observatorio de buitres", location:"Valderrobres", lat:40.8600, lng:0.1400, description:"Observatorio ÚNICO en el mundo en un muladar. Cada día 09:15h, cientos de buitres leonados alimentados por Buitreman. 15€.", image:"/img/buitres.png", longDescription:"El único observatorio de aves del mundo ubicado en un muladar. Cada día a las 09:15h, José Ramón Moragrega 'Buitreman' alimenta a cientos de buitres leonados mientras los visitantes observan desde un hide profesional. Posibilidad de alojamiento en masía rehabilitada. Apto para niños desde 4 años.", phone:"677 174 845", recommended:true, priceRange:"€", specialties:["Buitres leonados","Buitreman","Muladar único","Hide profesional","Alojamiento masía"], productClub:"cultura", externalUrl:"https://masdebunyol.com", externalLabel:"masdebunyol.com", tips:["Reserva obligatoria — llama al 677 174 845","Viste ropa oscura y no uses flash","Actividad a las 09:15h todos los días","15€ adultos, reducido para niños"], schedule:"Todos los días a las 09:15h. Reserva previa obligatoria." },
  { id:"via_ferrata", name:"Vía Ferrata Mas de Pau", category:"actividad", subcategory:"Vía Ferrata K2-K4", location:"Fuentespalda", lat:40.8090, lng:0.0200, description:"Vía ferrata con nivel K2 (principiantes) y opción K4 (avanzado). Ideal para iniciarse en la verticalidad.", specialties:["Nivel K2 principiante","Opción K4 avanzado","Vistas increíbles","Guías disponibles"], tips:["El nivel K2 es apto para principiantes","Lleva guantes y calzado de montaña"] },
  { id:"barranquismo_canaletes", name:"Barranquismo Canaletes", category:"actividad", subcategory:"Descenso de barrancos", location:"Horta de Sant Joan / Beceite", lat:40.82, lng:0.30, description:"Barranco de Canaletes: rápeles, toboganes y sifones en aguas turquesas. Apto desde 8 años — ideal iniciación.", image:"/img/barranquismo.png", longDescription:"El Barranco de Canaletes es perfecto para iniciarse en el barranquismo. Aguas turquesas, rápeles, toboganes naturales y sifones. Apto para niños a partir de 8 años. Varias empresas ofrecen guías.", recommended:true, specialties:["Aguas turquesas","Rápeles","Toboganes","Desde 8 años","Ideal iniciación"], tips:["Apto para niños desde 8 años","Se proporcionan neoprenos y cascos","Reserva con empresa local"] },
  { id:"matarranya_aventura", name:"Matarraña Aventura", category:"actividad", subcategory:"Multiaventura", location:"Cretas", lat:40.984, lng:0.171, description:"BTT guiado, senderismo, 4x4 por los Puertos, tiro con arco, kayak en Pantano Pena y Vía Verde en bici.", longDescription:"La empresa de turismo activo con más variedad del Matarraña. Desde rutas guiadas en BTT con alquiler de bicicletas hasta excursiones en 4x4 por los Puertos de Beceite. También organizan kayak, barranquismo, tiro con arco y gymkhanas.", recommended:true, specialties:["BTT guiado","Alquiler bicis","4x4 Puertos","Kayak","Tiro con arco","Barranquismo"], productClub:"cicloturismo", externalUrl:"https://matarrañaventura.com", externalLabel:"matarrañaventura.com" },
  { id:"matarranya_nautic", name:"Matarranya Nàutic (Senda)", category:"actividad", subcategory:"Deportes acuáticos", location:"Pantano de Pena", lat:40.8522, lng:0.1378, description:"Kayak, paddle surf, barcas y eBikes en el Pantano de Pena. También rutas 4x4, BTT y Segway + cata aceite.", image:"/img/kayak_pantano.png", longDescription:"Centro de deportes acuáticos en el Pantano de Pena. Alquiler de kayaks, paddle surf y barcas. También rutas interpretativas en 4x4, senderismo por los Puertos, alquiler BTT/eBikes y la experiencia Segway + cata de aceite en Mas dels Castellans.", recommended:true, specialties:["Kayak","Paddle Surf","Barcas","eBike","Segway + cata aceite","Rutas 4x4"], productClub:"cicloturismo", externalUrl:"https://websenda.com", externalLabel:"websenda.com" },
  { id:"geopixel", name:"Geopixel", category:"actividad", subcategory:"Rutas interpretativas", location:"Beceite", lat:40.828, lng:0.175, description:"Rutas interpretativas en 4x4 por los Puertos de Beceite. Descubre la geología y fauna.", specialties:["4x4 interpretativo","Senderismo guiado","Puertos de Beceite","Geología"] },
  { id:"les_roques_natura", name:"Les Roques Natura", category:"actividad", subcategory:"Aventura y ecoturismo", location:"Comarca del Matarraña", lat:40.846, lng:0.148, description:"Barranquismo, senderismo, BTT, ecoturismo y alquiler de bicicletas.", specialties:["Barranquismo","BTT","Ecoturismo","Alquiler bicis"] },
  { id:"hipica_mc", name:"Hípica MC", category:"actividad", subcategory:"Rutas a caballo", location:"Cretas", lat:40.985, lng:0.168, description:"Rutas a caballo por los paisajes del Matarraña. Diferentes duraciones: 1h, 2h, medio día o día completo.", specialties:["Rutas a caballo","1h a día completo","Olivos y viñedos","Principiantes"] },
  { id:"establo_crystal", name:"Establo de Crystal", category:"actividad", subcategory:"Rutas ecuestres", location:"Valderrobres", lat:40.875, lng:0.152, description:"Ruta de 4 horas por el río Matarraña entre almendros, olivos y viñedos. Paseos guiados.", specialties:["Ruta 4h río Matarraña","Almendros y olivos","Paseos guiados"] },
  { id:"inhospitak", name:"Inhospitak", category:"actividad", subcategory:"Paleontología", location:"Peñarroya de Tastavins", lat:40.760, lng:-0.035, description:"Centro de interpretación paleontológica con réplicas de dinosaurios. Ideal para familias con niños.", specialties:["Dinosaurios","Paleontología","Familias","Interactivo"], productClub:"cultura" },
];

// ─── BODEGAS Y ALMAZARAS ─────────────────────────────────────
export const bodegas: PointOfInterest[] = [
  { id:"mas_castellans", name:"Mas dels Castellans", category:"bodega", subcategory:"Oleoturismo y catas AOVE", location:"Calaceite", lat:41.0200, lng:0.1860, description:"Visitas a olivares centenarios + cata sensorial de AOVE + rutas en Segway. La experiencia oleoturística más completa.", image:"/img/cata_aceite.png", longDescription:"Visita olivos centenarios de variedades autóctonas, conoce el cultivo sostenible y disfruta de una cata sensorial de AOVE. También ruta en Segway por Calaceite con cata incluida (3h, máx 5 personas). Una experiencia única.", phone:"651 123 456", recommended:true, specialties:["Cata AOVE","Olivos centenarios","Ruta Segway + cata 3h","Cultivo sostenible"], productClub:"gastronomia", externalUrl:"https://masdelscastellans.es", externalLabel:"masdelscastellans.es", tips:["Reserva la ruta Segway + cata: 3 horas, máx 5 personas","La cata sensorial es una experiencia top","Incluye explicación de variedades autóctonas"] },
  { id:"venta_daubert", name:"Bodega Venta d'Aubert", category:"bodega", subcategory:"Bodega ecológica", location:"Cretas", lat:40.982, lng:0.172, description:"Bodega ecológica con visitas guiadas y cata de vinos. Viñedos propios en el Matarraña.", image:"/img/bodega.png", recommended:true, specialties:["Vinos ecológicos","Visita guiada","Cata de vinos","Viñedos propios"], productClub:"gastronomia", externalUrl:"https://ventadaubert.com", externalLabel:"ventadaubert.com" },
  { id:"a_maru", name:"Bodega A Maru", category:"bodega", subcategory:"Bodega artesanal", location:"Matarraña", lat:40.90, lng:0.10, description:"Bodega artesanal con visitas y catas. Sumérgete en la cultura del vino del Matarraña.", specialties:["Vinos artesanales","Visitas","Catas"], externalUrl:"https://amarubodegas.com", externalLabel:"amarubodegas.com" },
  { id:"mas_torubio", name:"Bodega Mas de Torubio", category:"bodega", subcategory:"Bodega familiar", location:"Matarraña", lat:40.87, lng:0.09, description:"Bodega familiar. Vinos orgánicos con visita guiada y cata incluida.", specialties:["Vinos orgánicos","Bodega familiar","Visita + cata"] },
  { id:"gourmet_matarranya", name:"Gourmet Matarranya", category:"bodega", subcategory:"Tienda gourmet", location:"Valderrobres", lat:40.8746, lng:0.1560, description:"Tienda de productores locales: vinos, jamones, aceites, embutidos directamente del productor.", specialties:["Vinos locales","Jamón de Teruel","AOVE","Embutidos"] },
];

// ─── TIENDAS DE PRODUCTOS LOCALES ────────────────────────────
export const shops: PointOfInterest[] = [
  { id:"lo_rebost", name:"Lo Rebost", category:"tienda", subcategory:"Productos locales", location:"Calaceite (Pza. España 12)", lat:41.0191, lng:0.1878, description:"Tienda de productos locales en la plaza principal de Calaceite. Todo lo mejor del Matarraña.", specialties:["Productos locales","Aceites","Conservas","Miel"] },
  { id:"sabores_arte", name:"Sabores con Arte", category:"tienda", subcategory:"Productos típicos", location:"Calaceite (Avda. Aragón 3)", lat:41.0185, lng:0.1895, description:"Productos típicos del Matarraña, Teruel y Aragón: vinos, cárnicos, quesos, conservas, miel y aceitunas.", specialties:["Vinos","Quesos","Conservas","Miel","Embutidos"] },
  { id:"casa_giner", name:"Casa Giner", category:"tienda", subcategory:"Productos regionales", location:"Valderrobres (Pza. España 3)", lat:40.8741, lng:0.1557, description:"Dos tiendas en Valderrobres con lo mejor de los productos regionales del Matarraña.", specialties:["Productos regionales","AOVE","Embutidos","Dulces"] },
  { id:"agrotienda", name:"Agrotienda Turismo Matarraña", category:"tienda", subcategory:"Productos y turismo", location:"Valderrobres (Pza. España 4)", lat:40.8739, lng:0.1559, description:"Productos turísticos y locales en la plaza principal de Valderrobres.", specialties:["Turismo","Artesanía","Productos locales"] },
  { id:"ca_la_mati", name:"Ca La Mati", category:"tienda", subcategory:"Recuerdos y gourmet", location:"Beceite (Arrabal del Puente 13)", lat:40.8288, lng:0.1738, description:"Tienda de recuerdos y productos típicos: embutidos, quesos y souvenirs del Matarraña.", specialties:["Souvenirs","Embutidos","Quesos","Recuerdos"] },
];

// ─── MUSEOS Y CULTURA ────────────────────────────────────────
export const culturalSpaces: PointOfInterest[] = [
  { id:"museo_juan_cabre", name:"Museo Juan Cabré", category:"cultura", subcategory:"Arqueología ibérica", location:"Calaceite", lat:41.0193, lng:0.1880, description:"Dedicado al arqueólogo Juan Cabré. Documentó los yacimientos íberos más importantes de la zona.", specialties:["Arqueología","Cultura ibérica","Juan Cabré"], productClub:"cultura" },
  { id:"museo_aceite", name:"Museo del Aceite", category:"cultura", subcategory:"Molino rehabilitado s.XVIII", location:"Calaceite", lat:41.0188, lng:0.1885, description:"Molino rehabilitado del siglo XVIII. Historia de la producción de aceite de oliva en la comarca.", specialties:["Historia del aceite","Molino s.XVIII","Oleoturismo"], productClub:"cultura" },
  { id:"ci_iberico", name:"Centro Interpretación Cultura Ibérica", category:"cultura", subcategory:"Centro interpretación", location:"Mazaleón", lat:41.0502, lng:0.0848, description:"Centro dedicado a la cultura ibérica. Ideal para entender los yacimientos de la zona.", specialties:["Cultura ibérica","Historia","Interpretación"], productClub:"cultura" },
  { id:"museo_lo_masmut", name:"Museo Etnológico Lo Masmut", category:"cultura", subcategory:"Etnología", location:"Peñarroya de Tastavins", lat:40.7605, lng:-0.0345, description:"Preserva las tradiciones y oficios del Matarraña. Herramientas, textiles y vida rural.", specialties:["Etnología","Tradiciones","Oficios","Vida rural"], productClub:"cultura" },
  { id:"santuario_virgen_fuente", name:"Santuario Virgen de la Fuente", category:"cultura", subcategory:"Arte mudéjar BIC", location:"Peñarroya de Tastavins", lat:40.7610, lng:-0.0340, description:"Santuario mudéjar Bien de Interés Cultural. Un tesoro escondido del Matarraña.", specialties:["Arte mudéjar","BIC","Arquitectura religiosa"], productClub:"cultura" },
  { id:"coveta_aigua", name:"La Coveta de l'Aigua", category:"cultura", subcategory:"Arte rupestre", location:"Fuentespalda", lat:40.810, lng:0.019, description:"Cueva con manifestaciones rupestres. Pinturas prehistóricas en un entorno natural excepcional.", specialties:["Arte rupestre","Prehistoria","Pinturas"], productClub:"cultura" },
];

// ─── SPA Y BIENESTAR ─────────────────────────────────────────
export const wellness: PointOfInterest[] = [
  { id:"torre_marques", name:"Torre del Marqués Hotel Spa", category:"bienestar", subcategory:"Spa 5★", location:"Monroyo", lat:40.8100, lng:-0.0500, description:"Hotel 5★ con spa de aguas termales, hammam turco, sauna, duchas bitérmicas y cabinas de masaje.", image:"/img/spa.png", longDescription:"El spa más exclusivo del Matarraña. Aguas termales, hammam turco, sauna finlandesa, tumbonas climatizadas y cabinas de masaje. Se puede privatizar el spa.", recommended:true, priceRange:"€€€", specialties:["Aguas termales","Hammam","Sauna","Masajes","Spa privado"], productClub:"bienestar", externalUrl:"https://hoteltorredelmarques.com", externalLabel:"hoteltorredelmarques.com" },
  { id:"lagaya_spa", name:"Lagaya Apartaments & Spa", category:"bienestar", subcategory:"Spa y masajes", location:"Valderrobres", lat:40.8755, lng:0.1545, description:"Spa con baño turco, sauna, hidromasaje y zona de masajes terapéuticos en Valderrobres.", recommended:true, priceRange:"€€", specialties:["Spa","Hammam","Sauna","Masajes","Boutique Spa"], productClub:"bienestar", externalUrl:"https://lagaya-apartaments.com", externalLabel:"lagaya-apartaments.com", schedule:"Mayores de 16 años" },
  { id:"mas_costa_spa", name:"Hotel Mas de la Costa", category:"bienestar", subcategory:"Spa rural", location:"Matarraña", lat:40.86, lng:0.13, description:"Hotel rural con spa: sauna, baño turco y piscina exterior con vistas a la sierra.", priceRange:"€€", specialties:["Sauna","Baño turco","Piscina exterior"], productClub:"bienestar" },
  { id:"uma_matarranya", name:"UMA Matarraña", category:"bienestar", subcategory:"Salud integral", location:"Matarraña", lat:40.87, lng:0.16, description:"Centro de salud integral: masajes variados, Tai Chi, Chi Kung y naturopatía.", specialties:["Masajes","Tai Chi","Chi Kung","Naturopatía"], productClub:"bienestar" },
  { id:"masana", name:"Masana Bienestar", category:"bienestar", subcategory:"Masajes", location:"Matarraña", lat:40.88, lng:0.15, description:"Centro de masajes y tratamientos de relajación y bienestar.", specialties:["Masajes terapéuticos","Relajación","Bienestar"], productClub:"bienestar", externalUrl:"https://masanabienestar.com", externalLabel:"masanabienestar.com" },
];
