import type { PointOfInterest } from './types';

// ─── NATURAL PLACES (34) ──────────────────────────────────────
export const places: PointOfInterest[] = [
  // ZONAS DE BAÑO
  { id:"pantano_pena", name:"Pantano de Pena", category:"bañarse", subcategory:"Embalse", location:"Beceite / Valderrobres", lat:40.8522, lng:0.1378, description:"Embalse rodeado de pinos, ideal para piraguas, patines acuáticos y paseos.", longDescription:"Paraje espectacular para disfrutar del baño y actividades acuáticas como piraguas y patines. Existe un camino que se puede rodear a pie o en bicicleta, disfrutando de unas vistas únicas de los Puertos de Beceite. En verano es un punto de encuentro para familias de toda la comarca.", image:"/img/pantano_pena.png", externalUrl:"https://www.comarcamatarranya.es/turismo/pantano-de-pena", externalLabel:"Comarca Matarraña", tips:["Lleva protector solar, no hay sombra en algunas zonas","Se puede alquilar piraguas en verano","El camino perimetral es ideal para bicicletas","Al atardecer los colores son espectaculares"], highlights:["Piraguas y patines","Camino perimetral","Vistas espectaculares","Ideal en familia"] },
  { id:"pesqueras", name:"La Pesquera", category:"bañarse", subcategory:"Pozas naturales", location:"Beceite", lat:40.8312, lng:0.1834, description:"Tramo del río Ulldemó con varias pozas de agua cristalina. Acceso regulado en verano.", longDescription:"Se le llama así a un tramo del río Ulldemó, donde se pueden encontrar varias pozas de agua cristalina para bañarse. En verano el acceso está regulado para preservar este entorno natural privilegiado.", image:"/img/pesquera.png", externalUrl:"https://www.beceite.es/la-pesquera", externalLabel:"Web Ayuntamiento Beceite", tips:["Madruga para no quedarte sin plaza","El agua está fría incluso en agosto","Lleva escarpines para las piedras","Ve entre semana si puedes"], highlights:["Pozas cristalinas","Río Ulldemó","Acceso regulado","Fotografía espectacular"], productClub:"bienestar" },
  { id:"assud_lledo", name:"L'Assud de Lledó", category:"bañarse", subcategory:"Azud", location:"Lledó", lat:40.978, lng:0.2217, description:"Azud en el río Algars, junto al acueducto de la Vía Verde.", longDescription:"Se ubica en el río Algars, al lado del acueducto de la Vía Verde Val de Zafán. Un lugar tranquilo y pintoresco ideal para combinar con un paseo por la Vía Verde.", highlights:["Junto al acueducto","Río Algars","Entorno tranquilo"] },
  { id:"salt", name:"El Salt", category:"bañarse", subcategory:"Cascada", location:"La Portellada", lat:40.8872, lng:0.0521, description:"Cascada de 20 metros del río Tastavins con una poza espectacular.", longDescription:"Cascada de 20 metros del río Tastavins, uno de los Puntos de Interés Geológico (PIG) más impresionantes de la comarca. En primavera, con el deshielo, es espectacular.", image:"/img/salt.png", externalUrl:"https://www.comarcamatarranya.es/turismo/el-salt-la-portellada", externalLabel:"Comarca Matarraña", tips:["Cuidado con el sendero resbaladizo","Espectacular después de lluvias","Ideal para fotografía con trípode"], highlights:["Cascada 20m","Poza natural","PIG reconocido","Espectacular en primavera"], productClub:"bienestar" },
  { id:"toll_verdura", name:"Toll de Verdura", category:"bañarse", subcategory:"Poza", location:"Beceite", lat:40.819, lng:0.175, description:"Azud en el río Matarraña, camino hacia el Parrizal.", highlights:["Camino al Parrizal","Río Matarraña","Aguas cristalinas"] },
  { id:"piscina_beceite", name:"Piscina Natural de Beceite", category:"bañarse", subcategory:"Poza", location:"Beceite", lat:40.826, lng:0.179, description:"En la ribera del Algars, entre Valderrobres y Arnes.", highlights:["Río Algars","Fácil acceso","Ideal para familias"] },
  { id:"toll_galero", name:"Toll del Galero", category:"bañarse", subcategory:"Cascada y Poza", location:"Beceite", lat:40.835, lng:0.177, description:"Dos cascadas con pozas en las inmediaciones de Beceite.", highlights:["Dos pozas naturales","Cascadas","Menos masificado"] },
  { id:"toll_vidre", name:"Toll del Vidre", category:"bañarse", subcategory:"Cascada y Poza", location:"Arnes (acceso)", lat:40.85, lng:0.23, description:"Cascada y poza en la ribera del Algars, acceso por Arnes.", highlights:["Cascada","Poza cristalina","Acceso por Arnes"] },
  { id:"toll_font_rabasa", name:"Toll Font de Rabasa", category:"bañarse", subcategory:"Poza", location:"Arens de Lledó", lat:40.96, lng:0.205, description:"Poza del río Algars, a pocos metros de Arens de Lledó.", highlights:["Río Algars","Cerca de Arens de Lledó"] },
  // NATURALEZA
  { id:"parrizal", name:"El Parrizal", category:"naturaleza", subcategory:"Pasarelas y Cañón", location:"Beceite", lat:40.8037, lng:0.1983, description:"Impresionante sendero de pasarelas sobre el río Matarraña entre paredes de roca de +60m.", longDescription:"El Parrizal de Beceite es sin duda el lugar más emblemático del Matarraña. Un sendero de pasarelas de madera te lleva por encima del río Matarraña, entre imponentes paredes de roca de más de 60 metros de altura. Red Natura 2000. Es la visita imprescindible.", routeInfo:"Camino Lineal · 11 km (ida y vuelta)", image:"/img/parrizal.png", externalUrl:"https://www.elparrizal.es", externalLabel:"Reservar entrada en elparrizal.es", tips:["Reserva tu entrada online en temporada alta","Lleva calzado que se pueda mojar","Madruga para evitar colas","Duración: 3-4 horas"], highlights:["Pasarelas sobre el río","Paredes de +60m","Red Natura 2000","Imprescindible"], recommended:true, productClub:"cicloturismo" },
  { id:"roques_masmut", name:"Roques del Masmut", category:"naturaleza", subcategory:"Monumento Natural", location:"Peñarroya de Tastavins", lat:40.755, lng:-0.0408, description:"Conglomerados rojos impresionantes, hogar de buitres leonados.", routeInfo:"PR-TE 157 Circular · 11 km", image:"/img/roques_masmut.png", externalUrl:"https://www.comarcamatarranya.es/turismo/roques-del-masmut", externalLabel:"Comarca Matarraña", tips:["Lleva prismáticos para los buitres","La luz del atardecer es perfecta","Ruta de dificultad media"], highlights:["Conglomerados rojos","Buitres leonados","PIG reconocido"], productClub:"cicloturismo" },
  { id:"fenellassa", name:"La Fenellassa", category:"naturaleza", subcategory:"Arte Rupestre UNESCO", location:"Beceite", lat:40.81, lng:0.19, description:"Abrigo con pinturas rupestres Patrimonio UNESCO en los Puertos de Beceite.", externalUrl:"https://www.patrimonioculturaldearagon.es/arte-rupestre", highlights:["Patrimonio UNESCO","Puertos de Beceite","Miles de años"] },
  // RUTAS
  { id:"via_verde", name:"Vía Verde Val de Zafán", category:"ruta", subcategory:"Camino Natural", location:"Puebla de Híjar → Tortosa", lat:40.9419, lng:0.0461, description:"Antiguo trazado ferroviario: 135 km a pie o en bici cruzando viaductos y túneles.", routeInfo:"Lineal · 135 km (total)", image:"/img/via_verde.png", externalUrl:"https://www.viasverdes.com/itinerarios/itinerario_detalle.asp?id=44", externalLabel:"viasverdes.com", tips:["El tramo del Matarraña es el más bonito","Alquiler de bicis disponible","Los túneles son frescos: lleva capa","Ideal para familias — desnivel suave"], highlights:["Viaductos","Túneles","Apto familias","Alquiler bicis"], recommended:true, productClub:"cicloturismo" },
  { id:"castillo_almudefar", name:"Castillo de Almudéfar", category:"ruta", subcategory:"Sendero PR", location:"Arens de Lledó", lat:40.955, lng:0.21, description:"Ruta hasta las ruinas del castillo con vistas panorámicas.", routeInfo:"PR-TE 167 · 15,9 km", highlights:["Ruinas de castillo","Vistas panorámicas"] },
  { id:"ermita_montserrate", name:"Ermita de Montserrate", category:"ruta", subcategory:"Sendero PR", location:"Fórnoles", lat:40.92, lng:0.03, description:"Ruta corta y fácil hasta la ermita, perfecta para familias.", routeInfo:"PR-TE 161 · 5,4 km", highlights:["Ruta familiar","Ermita histórica","Apta para niños"] },
  { id:"fortins_cabrera", name:"Fortins de Cabrera", category:"ruta", subcategory:"Sendero PR", location:"Beceite", lat:40.828, lng:0.17, description:"Subida corta a los fortines de las Guerras Carlistas.", routeInfo:"PR-TE 154 · 1,6 km", tips:["Solo 1,6 km — perfecta con niños","Mejor al atardecer"], highlights:["Fortines carlistas","Ruta muy corta","Vistas de Beceite"] },
  { id:"pena_galera", name:"Ascensión a Peña Galera", category:"ruta", subcategory:"Ascensión", location:"Beceite", lat:40.79, lng:0.205, description:"Circular exigente hasta la cima con vistas de 360° sobre los Puertos.", routeInfo:"PR-TE 151 Circular · 8,2 km", tips:["Ruta exigente: lleva mín. 2 litros de agua","Evita días de viento fuerte","Salida temprana en verano"], highlights:["Vistas 360°","Puertos de Beceite","Se ve el Mediterráneo"] },
  { id:"mola_lino", name:"Mola de Lino", category:"ruta", subcategory:"Ascensión", location:"Beceite", lat:40.785, lng:0.195, description:"Ascensión a una de las cumbres más emblemáticas de los Puertos.", routeInfo:"PR-TE 150 · 8,6 km", highlights:["Cumbre icónica","Pinares mediterráneos"] },
  { id:"gr8", name:"GR-8 Matarraña", category:"ruta", subcategory:"Gran Recorrido", location:"Beceite – Monroyo", lat:40.84, lng:0.12, description:"70 km de Gran Recorrido atravesando el corazón del Matarraña.", routeInfo:"GR-8 · 70 km", externalUrl:"https://senderosturisticos.turismodearagon.com", highlights:["70 km","Varias etapas","Diversidad paisajística"] },
  { id:"matarrana_algars", name:"Camino Natural Matarraña – Algars", category:"ruta", subcategory:"Circular", location:"Comarca del Matarraña", lat:40.88, lng:0.11, description:"¡197 km en 13 etapas! La gran circular de la comarca.", routeInfo:"Circular · 197 km (13 etapas)", highlights:["197 km","13 etapas","Conecta toda la comarca"] },
  { id:"btt_llaurador", name:"Ruta BTT del Llaurador", category:"ruta", subcategory:"BTT", location:"Comarca del Matarraña", lat:40.91, lng:0.08, description:"Ruta circular de mountain bike de 49 km por caminos rurales.", routeInfo:"BTT Circular · 49 km", highlights:["49 km","Mountain Bike","Olivos centenarios"] },
  { id:"els_estrets", name:"Ruta de Els Estrets", category:"ruta", subcategory:"Sendero PR", location:"Ráfales", lat:40.865, lng:0.005, description:"Ruta por los estrechos del río, con paredes de roca a ambos lados.", routeInfo:"PR Lineal · 8 km", highlights:["Estrechos del río","Paredes de roca"] },
  // HISTORIA
  { id:"poblado_san_antonio", name:"Poblado Íbero de San Antonio", category:"historia", subcategory:"Yacimiento Arqueológico", location:"Calaceite", lat:41.0186, lng:0.1878, description:"Uno de los asentamientos íberos más importantes del territorio Ilercavón.", externalUrl:"https://www.calaceite.es/turismo", tips:["Visita guiada recomendada","Combínalo con Calaceite"], highlights:["Poblado Ilercavón","Bien de Interés Cultural","Vistas panorámicas"], productClub:"cultura" },
  { id:"castillo_valderrobres", name:"Castillo de Valderrobres", category:"historia", subcategory:"Gótico Levantino", location:"Valderrobres", lat:40.8744, lng:0.1558, description:"Joya del gótico levantino aragonés y Santa María la Mayor.", longDescription:"El conjunto de Santa María la Mayor y el castillo de Valderrobres es la joya de la corona del gótico levantino aragonés. En su interior, exposiciones con reproducciones de Goya, El Greco y Velázquez.", image:"/img/valderrobres.png", externalUrl:"https://www.castillodevalderrobres.com", externalLabel:"Reservar visita guiada", tips:["Visita guiada incluida","Vistas desde la torre espectaculares","Entrada: 8€"], highlights:["Gótico levantino","Castillo-palacio","Monumento más visitado"], recommended:true, productClub:"cultura" },
  { id:"els_castellans", name:"Els Castellans", category:"historia", subcategory:"Yacimiento", location:"Cretas – Calaceite", lat:41.005, lng:0.17, description:"Poblado íbero entre Cretas y Calaceite con torres defensivas.", highlights:["Torres defensivas","2.000 años de historia"] },
  { id:"tumbas_clot", name:"Tumbas Altomedievales de El Clot", category:"historia", subcategory:"Necrópolis", location:"Mazaleón", lat:41.05, lng:0.085, description:"Necrópolis altomedieval con tumbas excavadas en la roca.", routeInfo:"SL-TE-18 · 6 km", highlights:["Tumbas en roca","Época altomedieval"] },
  { id:"ruta_gotico", name:"Ruta del Gótico Levantino", category:"historia", subcategory:"Arquitectura", location:"Varios pueblos", lat:40.88, lng:0.14, description:"Recorrido por las iglesias, castillos y ermitas góticas de la comarca.", externalUrl:"https://www.comarcamatarranya.es/turismo/patrimonio", highlights:["Gótico, Mudéjar, Renacimiento","Ruta por toda la comarca"], productClub:"cultura" },
  // PUEBLOS
  { id:"valderrobres", name:"Valderrobres", category:"pueblo", subcategory:"Capital de comarca", location:"Matarraña", lat:40.874, lng:0.156, description:"La capital del Matarraña con puente medieval y castillo imponente.", image:"/img/valderrobres.png", externalUrl:"https://www.valderrobres.es", highlights:["Puente medieval","Castillo gótico","Capital del Matarraña"], recommended:true, productClub:"cultura" },
  { id:"calaceite", name:"Calaceite", category:"pueblo", subcategory:"Pueblo con encanto", location:"Matarraña", lat:41.019, lng:0.188, description:"Uno de los pueblos más bonitos de Aragón, cuna de la cultura íbera.", image:"/img/calaceite.png", externalUrl:"https://www.calaceite.es", highlights:["Piedra dorada","Portales-capilla","Conjunto Histórico-Artístico"], recommended:true, productClub:"cultura" },
  { id:"beceite", name:"Beceite", category:"pueblo", subcategory:"Puerta de los Puertos", location:"Matarraña", lat:40.829, lng:0.174, description:"La puerta de entrada a los Puertos, rodeado de montañas y ríos.", image:"/img/beceite.png", externalUrl:"https://www.beceite.es", highlights:["Puerta de los Puertos","Base de excursiones","Fábrica Papel s.XVIII"], productClub:"cultura" },
  { id:"la_fresneda", name:"La Fresneda", category:"pueblo", subcategory:"Pueblo con encanto", location:"Matarraña", lat:40.925, lng:0.07, description:"Pueblo señorial con la Casa de la Encomienda renacentista.", image:"/img/la_fresneda.png", externalUrl:"https://www.lafresneda.es", highlights:["Casa de la Encomienda","Renacimiento aragonés"], productClub:"cultura" },
  { id:"cretas", name:"Cretas", category:"pueblo", subcategory:"Pueblo con encanto", location:"Matarraña", lat:40.983, lng:0.17, description:"Pueblo medieval con portales, ermitas y el encanto del Matarraña.", image:"/img/cretas.png", highlights:["Portales-capilla","Ermita histórica","Calles empedradas"], productClub:"cultura" },
];
